spring.application.name=Softwaretest
spring.datasource.url=jdbc:h2:file:./data/immobilien-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui
